### ISSUE TITLE
estou com um problema, a calculadora não está executando o código, comecou a dar bugs no finalzinho do projeto. Dá isso no terminal:

### ISSUE THREAD

**Issue by felipecastrosales** [cod3rcursos/youtube#11]
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'List<String>' is not a subtype of type 'String'

When the exception was thrown, this was the stack: 
#0      Memory._setOperation (package:calculator/models/memory.dart:47:7)
#1      Memory.applyCommand (package:calculator/models/memory.dart:20:7)
#2      _CalculatorState._onPressed.<anonymous closure> (package:calculator/screens/calculator.dart:19:14)
#3      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
#4      _CalculatorState._onPressed (package:calculator/screens/calculator.dart:18:5)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#71251
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(384.0, 756.8)
  finalLocalPosition: Offset(59.5, 40.0)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by felipecastrosales** [comment]
Consegui solucionar, dei um "flutter pub get" no terminal e a aplicação voltou ao normal. 😀👌
